name: VoteRestart
version: 1.0-SNAPSHOT
main: io.github.mazkaaa.voterestart.VoteRestart
api-version: 1.13
authors: [mazkaaa]
description: Vote Restart
commands:
  voterestart:
    description: Start the voting
depend: [Essentials]
